### ISSUE TITLE
Syntax error when running "node meal_calculator.js"

### ISSUE THREAD

**Issue by trystant** [clanam/thinkful-node-meal-calculator#1]
When attempting to run `node meal_calculator.js` on my system, I get these results:

```
[mnyon@mnyon ~/code/thinkful-node-meal-calculator (git::master) ] node meal_calculator.js
/Users/mnyon/code/thinkful-node-meal-calculator/meal_calculator.js:57
Meal.prototype.printCostBreakdown = printCostBreakdown() {
                                                         ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

This syntax error should be fixed.

**Comment by clanam** [comment]
fixed >.<'

**Comment by trystant** [comment]
Good job!
